[tools]
bun = "1.2.21"

[env]
NODE_ENV = "development"

[tasks.install]
description = "Install dependencies"
run = "bun install"

[tasks.dev]
description = "Run in development mode (hot reloading enabled)"
run = "bun run dev"

[tasks.build]
description = "Builds app for static serving"
run = "bun run build --sourcemap=linked"
